ProdutoMVC/Controllers/PedidoController.cs
using BematechMVC.Models;
using Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BematechMVC.Controllers
{
    public class PedidoController : BaseController
    {
        // GET: Pedido
        public ActionResult Index()
        {
            BuscaPedidoViewModel model = new BuscaPedidoViewModel();
            model.ListaCliente.AddRange(new SelectList(_clienteService.GetAll(), "Id_Cliente", "Nome"));
            model.ListaPedidos = _pedidoService.GetAll();
            return View(model);
        }

        public ActionResult CriarPedido()
        {
            CriarPedidoViewModel model = new CriarPedidoViewModel();
            model.ListaCliente.AddRange(new SelectList(_clienteService.GetAll(), "Id_Cliente", "Nome"));
            model.ListaProduto.AddRange(new SelectList(_produtoService.GetAll(), "Id_Produto", "Descricao"));
            return View(model);
        }

        [HttpPost]
        public ActionResult CriarPedido(CriarPedidoViewModel model)
        {
            try
            {
                if (model.DataEntrega.HasValue) {
                    Pedido pedido = new Pedido();
                    pedido.DataEntrega = model.DataEntrega.Value;
                    if (model.IdCliente != -1) {
                        pedido.Cliente_Id = model.IdCliente;
                    }
                    else
                    {
                        pedido.Cliente = null;
                    }
                    pedido.ListaProduto = model.PedidoItem.Select(s => new PedidoItem(s.Quantidade, s.Produto.IdProduto, s.ValorTotal)).ToList();
                    pedido.ValorTotal = pedido.ListaProduto.Sum(s => s.ValorTotal);
                    _pedidoService.Add(pedido);
                }
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                model.ListaCliente.AddRange(new SelectList(_clienteService.GetAll(), "Id_Cliente", "Nome"));
                model.ListaProduto.AddRange(new SelectList(_produtoService.GetAll(), "Id_Produto", "Descricao"));
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult ObterProduto(int IdProduto)
        {
            var produto = _produtoService.GetById(IdProduto);
            return Json(produto);
        }

        [HttpPost]
        public JsonResult ObterPedidos(BuscaPedidoViewModel model)
        {
            BuscaPedido buscaPedido = new BuscaPedido();
            buscaPedido.DataFinal = model.DataFinal;
            buscaPedido.DataInicial = model.DataInicial;
            buscaPedido.IdCliente = model.IdCliente;
            buscaPedido.NumeroPedido = model.IdPedido;
            var pedidos = _pedidoService.GetByModel(buscaPedido);
            IEnumerable<ListaBuscaPedidoViewModel> retorno = new List<ListaBuscaPedidoViewModel>();
            retorno = pedidos.Select(s => new ListaBuscaPedidoViewModel(s.Id_Pedido.ToString(), s.Cliente != null ? s.Cliente.Nome : "Cliente Generico", s.ValorTotal)).ToList();
            return Json(retorno);
        }
    }
}

ProdutoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Teste prático", "Index", "Pedido", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Busca de Pedido", "Index", "Pedido")</li>
                    <li>@Html.ActionLink("Cadastrar Pedido", "CriarPedido", "Pedido")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/dataTable")
    @RenderSection("scripts", required: false)
</body>
</html>